# Generated by Django 4.2.16 on 2025-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-caf347e61cea4d0e9669111e94b69bcb', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-f9382246b3ff47c1b7a7f03df2724eaf', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
