# Generated by Django 4.2.16 on 2025-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_agent_name_alter_network_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-fbfa4c2afb5d4f649e63d694fa7815c5', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-f2b8908f8a074896985b01bde0a2cb0e', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
