# Generated by Django 4.2.16 on 2025-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_agent_name_alter_network_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-cecf0eedaed740a385aef90f256e51bf', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-bb67b507991f4bd1b5402414769d7274', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
