# Generated by Django 4.2.16 on 2025-05-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_agent_name_alter_network_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='agent-e603b14257cf4c2ebe08ab2e7bc7380e', help_text='Agent name, can be generated automatically.', max_length=64),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(default='netowrk-e468644f181d4a3181e6558a37672762', help_text='network name, can be generated automatically.', max_length=64),
        ),
    ]
