site_name: Hyperledger Cello
repo_name: "hyperledger/cello"
repo_url: "https://github.com/hyperledger/cello"
dev_addr: 0.0.0.0:8000
theme:
  name: "material"
  logo: "images/favicon.png"
  favicon: "images/favicon.png"
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: "light-blue"
      accent: "light-blue"
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: "light-blue"
      accent: "light-blue"
  font:
    text: "Ubuntu Sans"
    code: "Ubuntu Sans Mono"
markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - pymdownx.critic:
      mode: view
docs_dir: docs
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Design:
      - Architecture: design/arch.md
  - Tutorials:
      - "Lesson 0: Introduction": tutorials/introduction.md
      - "Lesson 1: Prerequisites": tutorials/prerequisites.md
      - "Lesson 2: Server": tutorials/server.md
      - "Lesson 3: Agent": tutorials/agent.md
      - "Lesson 4: User & Organization": tutorials/organization.md
      - "Lesson 5: Agent, Network, & Node": tutorials/node.md
      - "Lesson 6: Channel": tutorials/channel.md
  - Reference:
      - Configuration:
          - Server Configuration: reference/configuration/server.md
      - Commands:
          - make: reference/commands/make.md
  - Contribute: contributing.md
  - FAQ:
      - faq.md
  - Release Notes:
      - release_note.md
plugins:
 - search
 - mermaid2
#  - minify:
#      minify_html: true
#  - pdf-export:
#      media_type: print
#      combined: true
#      enabled_if_env: ENABLE_PDF_EXPORT
