# Generated by Django 4.2.16 on 2025-09-13 00:52

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.UUIDField(default=common.utils.make_uuid, help_text='User ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', help_text='User Role', max_length=64),
        ),
    ]
