---
- name: Query service ports
  shell: >-
    kubectl --kubeconfig kubeconfig --namespace {{ namespace }} get services
    | grep LoadBalancer | awk '{print $1, $5, $4}'
  register: ports
  args:
    chdir: "{{ playbook_dir }}/../../vars/"

- set_fact:
    uniquehosts: []
    k8sports: []
    sports: {}

- set_fact:
    k8sports: >-
      {{ k8sports +
      [{ 'name':item.split(' ')[0], 'host': (item.split(' ')[2]),
         'value':(item.split(' ')[1]|replace('/TCP','')).split(',') }] }}
  with_items: "{{ ports.stdout_lines }}"

- set_fact:
    uniquehosts: >-
      {{ uniquehosts + [item.host] }}
  with_items: "{{ k8sports }}"

- set_fact:
    sports: >-
      {{ k8sports | subelements('value', skip_missing=True) }}

- set_fact:
    k8sports: {}
    k8shosts: {}

- set_fact:
    k8sports: >-
      {{ k8sports|combine( {item[0].name+':'+item[1].split(':')[0]:item[1].split(':')[1]} ) }}
    k8shosts: >-
      {{ k8shosts|combine( {item[0].name:item[0].host} ) }}
  with_items: "{{ [sports] }}"

- set_fact:
    uniquehosts: "{{ uniquehosts | unique }}"

- debug:
    var: k8sports
- debug:
    var: k8shosts
- debug:
    var: uniquehosts