# Generated by Django 4.2.16 on 2026-01-19 08:34

import common.utils
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, help_text='Organization ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization Name', unique=True, validators=[common.validators.validate_host])),
                ('agent_url', models.CharField(default=None, help_text='Organization Agent URL', unique=True, validators=[common.validators.validate_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
