# Generated by Django 4.2.16 on 2025-08-31 11:41

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, help_text='ID of organization', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of organization', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msp', models.TextField(help_text='msp of organization', null=True)),
                ('tls', models.TextField(help_text='tls of organization', null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
