# Generated by Django 4.2.16 on 2025-09-07 10:03

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Name of organization', max_length=64, unique=True, validators=[
                common.validators.validate_host]),
        ),
    ]
