# Generated by Django 4.2.16 on 2025-08-31 11:41

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, editable=False, help_text='ID of Channel', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='name of channel', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Create time of Channel')),
                ('orderers', models.ManyToManyField(help_text='Orderer list in the channel', to='node.node')),
                ('organizations', models.ManyToManyField(help_text='the organization of the channel', related_name='channels', to='organization.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
