# Generated by Django 4.2.16 on 2026-01-19 08:36

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, editable=False, help_text='Channel ID', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Channel Name', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Channel Creation Timestamp')),
                ('orderers', models.ManyToManyField(help_text='Channel Orderers', to='node.node')),
                ('organizations', models.ManyToManyField(help_text='Channel Organizations', related_name='channels', to='organization.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
