# Generated by Django 4.2.16 on 2026-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('node', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='orderers',
            field=models.ManyToManyField(help_text='Channel Orderers', to='node.node'),
        ),
        migrations.AddField(
            model_name='channel',
            name='organizations',
            field=models.ManyToManyField(help_text='Channel Organizations', related_name='channels', to='organization.organization'),
        ),
    ]
