# Generated by Django 4.2.16 on 2025-08-31 11:41

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, help_text='ID of node', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Node name', max_length=64)),
                ('type', models.CharField(choices=[('orderer', 'Orderer'), ('peer', 'Peer')], help_text='Node type', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Create time of network')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('failed', 'Failed')], default='created', help_text='Status of node', max_length=64)),
                ('config_file', models.TextField(help_text='Config file of node', null=True)),
                ('msp', models.TextField(help_text='msp of node', null=True)),
                ('tls', models.TextField(help_text='tls of node', null=True)),
                ('cid', models.CharField(default='', help_text='id used in agent, such as container id', max_length=256)),
                ('agent', models.ForeignKey(help_text='Agent of node', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='agent.agent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
