# Generated by Django 4.2.16 on 2025-09-28 23:48

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, help_text='Node ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Node Name', max_length=64)),
                ('type', models.CharField(choices=[('PEER', 'Peer'), ('ORDERER', 'Orderer')], help_text='Node Type', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Node Creation Timestamp')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='CREATED', help_text='Node Status', max_length=64)),
                ('config_file', models.TextField(help_text='Node Config File', null=True)),
                ('msp', models.TextField(help_text='Node MSP', null=True)),
                ('tls', models.TextField(help_text='Node TLS', null=True)),
                ('organization', models.ForeignKey(help_text='Organization Nodes', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='organization.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
