# Generated by Django 4.2.16 on 2025-09-13 00:52

import common.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_name'),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='agent',
        ),
        migrations.AddField(
            model_name='node',
            name='organization',
            field=models.ForeignKey(default=None, help_text='Organization Nodes', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='cid',
            field=models.CharField(default='', help_text='Node Container ID', max_length=256),
        ),
        migrations.AlterField(
            model_name='node',
            name='config_file',
            field=models.TextField(help_text='Node Config File', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Node Creation Timestamp'),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.UUIDField(default=common.utils.make_uuid, help_text='Node ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='msp',
            field=models.TextField(help_text='Node MSP', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(help_text='Node Name', max_length=64),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('failed', 'Failed')], default='created', help_text='Node Status', max_length=64),
        ),
        migrations.AlterField(
            model_name='node',
            name='tls',
            field=models.TextField(help_text='Node TLS', null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('orderer', 'Orderer'), ('peer', 'Peer')], help_text='Node Type', max_length=64),
        ),
    ]
