name: Code Check CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Install Nodejs dependencies
        working-directory: src/dashboard
        run: |
          yarn install --frozen-lockfile
      - name: Check code
        run: make check
