name: Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start Dashboard, DB, and API Engine
        run: docker compose -f docker-compose.dev.yaml up -d --build

      - name: Start Hyperledger Fabric Agent
        working-directory: src/agents/hyperledger-fabric
        run: |
          docker build -t cello-hyperledger-fabric-agent .
          docker run -d --network cello-net -v /var/run/docker.sock:/var/run/docker.sock --name cello-hyperledger-fabric-agent cello-hyperledger-fabric-agent

      - name: Build Hyperledger Fabric Node
        working-directory: src/nodes/hyperledger-fabric
        run: docker build -t hyperledger/fabric:2.5.15 .

      - name: Run newman tests
        working-directory: tests/postman
        run: docker compose up --abort-on-container-exit

      - name: Stop Hyperledger Fabric Chaincode
        run: docker ps -q --filter "name=dev-peer0.org1.foo.com-basic_1.0" | xargs -r docker stop

      - name: Stop Hyperledger Fabric Nodes
        run: docker stop orderer0.foo.com peer0.org1.foo.com

      - name: Stop Hyperledger Fabric Agent
        run: docker stop cello-hyperledger-fabric-agent

      - name: Stop Dashboard, DB, and API Engine
        run: docker compose -f docker-compose.dev.yaml down -v

      - name: Clean up
        if: always()
        run: docker system prune -a -f
