# Generated by Django 4.2.16 on 2026-01-19 08:36

import chaincode.models
import common.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('node', '0001_initial'),
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chaincode',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, editable=False, help_text='Chaincode ID', primary_key=True, serialize=False, unique=True)),
                ('package_id', models.CharField(editable=False, help_text='Chaincode Package ID', max_length=128, unique=True)),
                ('package', models.FileField(help_text='Chaincode Package', upload_to=chaincode.models.get_package_path)),
                ('name', models.CharField(help_text='Chaincode Name', max_length=128)),
                ('version', models.CharField(help_text='Chaincode Version', max_length=128)),
                ('sequence', models.IntegerField(help_text='Chaincode Sequence', validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(help_text='Chaincode Label', max_length=128)),
                ('language', models.CharField(help_text='Chaincode Language', max_length=128)),
                ('init_required', models.BooleanField(default=False, help_text='Whether Chaincode Initialization Required')),
                ('signature_policy', models.CharField(blank=True, help_text='Chaincode Signature Policy', null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('INSTALLED', 'Installed'), ('APPROVED', 'Approved'), ('COMMITTED', 'Committed')], default='CREATED', help_text='Chaincode Status', max_length=16)),
                ('description', models.CharField(blank=True, help_text='Chaincode Description', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Chaincode Creation Timestamp')),
                ('channel', models.ForeignKey(help_text='Chaincode Channel', on_delete=django.db.models.deletion.CASCADE, related_name='chaincodes', to='channel.channel')),
                ('creator', models.ForeignKey(help_text='Chaincode Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('peers', models.ManyToManyField(help_text='Chaincode Installed Peers', to='node.node')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
