# Generated by Django 4.2.16 on 2026-02-17 14:39

import chaincode.models
import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaincode',
            fields=[
                ('id', models.UUIDField(default=common.utils.make_uuid, editable=False, help_text='Chaincode ID', primary_key=True, serialize=False, unique=True)),
                ('package_id', models.CharField(editable=False, help_text='Chaincode Package ID', max_length=128)),
                ('package', models.FileField(help_text='Chaincode Package', upload_to=chaincode.models.get_package_path)),
                ('name', models.CharField(help_text='Chaincode Name', max_length=128)),
                ('version', models.CharField(help_text='Chaincode Version', max_length=128)),
                ('sequence', models.IntegerField(help_text='Chaincode Sequence', validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(help_text='Chaincode Label', max_length=128)),
                ('language', models.CharField(help_text='Chaincode Language', max_length=128)),
                ('init_required', models.BooleanField(default=False, help_text='Whether Chaincode Initialization Required')),
                ('signature_policy', models.CharField(blank=True, help_text='Chaincode Signature Policy', null=True)),
                ('description', models.CharField(blank=True, help_text='Chaincode Description', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Chaincode Creation Timestamp')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
