# Generated by Django 4.2.16 on 2026-02-17 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chaincode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaincode',
            name='channel',
            field=models.ForeignKey(help_text='Chaincode Channel', on_delete=django.db.models.deletion.CASCADE, related_name='chaincodes', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='chaincode',
            name='creator',
            field=models.ForeignKey(help_text='Chaincode Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
