# Generated by Django 4.2.16 on 2025-09-28 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaincode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaincode',
            name='creator',
            field=models.ForeignKey(help_text='Chaincode Creator', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chaincode',
            name='peers',
            field=models.ManyToManyField(help_text='Chaincode Installed Peers', to='node.node'),
        ),
    ]
