---
# The following defines a fabric network with 6 peers, 4 orderers
fabric:
  # options are "solo", "kafka", "etcdraft" (etcdraft support from 2.0.0)
  # for consensus_type, default is kafka
  consensus_type: "etcdraft"
  # options are "goleveldb", "CouchDB", default is goleveldb
  peer_db: "goleveldb"
  # options are "true", "false", "client" default is true
  tls: true
  generate_certs: true
  logging_level: "ERROR"
  metrics: false
  k8s:
    storageclass: "default"
    storagecapacity: "20Gi"
    shared_storage: false
    exposeserviceport: true
    # only used when exposeserviceport set to be true
    # the value could be NodePort or LoadBalancer
    servicetype: NodePort

  # Peer environment variables to override core.yaml values
  # variables should be in the peer readable format like shown below
  peersettings:
    CORE_LEDGER_STATE_COUCHDBCONFIG_WARMINDEXESAFTERNBLOCKS: "10"

  # Orderer configuration and environment variables to override
  # configtx.yaml and orderer.yaml values. ordererenv will take the
  # environment variables in the orderer readable format for example:
  # ORDERER_GENERAL_TLS_ENABLED=true
  orderersettings:
    config:
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 500
        AbsoluteMaxBytes: "98 MB"
        PreferredMaxBytes: "512 KB"
    ordererenv:
  kafkasettings:
    MESSAGE_MAX_BYTES: "103809024"
    MAX_REQUEST_SIZE: "104857600"
    REPLICA_FETCH_MAX_BYTES: "103809024"
    UNCLEAN_LEADER_ELECTION_ENABLE: "true"
    MIN_INSYNC_REPLICAS: "2"
    DEFAULT_REPLICATION_FACTOR: "3"
  raftsettings:
    Options:
      TickInterval: "500ms"
      ElectionTick: 10
      HeartbeatTick: 1
      MaxInflightBlocks: 5
      SnapshotIntervalSize: "100 MB"

  # The following section defines how the fabric network is going to be made up
  # cas indicates certificate authority containers
  # peers indicates peer containers
  # orderers indicates orderer containers
  # kafka indicates kafka containers
  # all names must be in lower case. Numeric characters cannot be used to start
  # or end a name. Character dot (.) can only be used in names of peers and orderers.
  network:
    components:
      cas:
        - ca1st.orga
        - ca1st.orgb
        - ca1st.orgc
        - ca1st.orgd
      peers:
        - anchor@peer1st.orga
        - anchor@peer1st.orgb
        - worker@peer2nd.orga
        - worker@peer2nd.orgb
        - worker@peer3rd.orga
        - worker@peer3rd.orgb
      orderers:
        - orderer1st.orgc
        - orderer1st.orgd
        - orderer2nd.orgc
        - orderer2nd.orgd

  # the container tag for main fabric components such as orderer, peer,
  # tools and chaincode. If left blank, then fabric components will be built
  # from the latest fabric source code with the combination of the refspec
  # specified above. If it is not empty, then its values must be the full
  # container tag like the following:
  #     x86_64-1.1.0-alpha                         # alpha release
  #     DAILY_STABLE                               # daily stable
  #     DEV_STABLE                                 # dev stable
  #     s390x-0.4.2                                # release 0.4.2 for s390x
  #     048c91eb47812582f36665fbea3d7e0e68e396bf   # commit build
  #     x86_64-1.0.0-snapshot-8d3275f              # snapshot build
  #     1.4.4                                      # release 1.4.4
  baseimage_tag: "1.4.4"

  # The container tag for accessory fabric components such as kafka,
  # zookeeper and couchdb.
  helper_tag: "0.4.18"

  # ca node release and setting
  ca:
    admin: "admin"
    adminpw: "adminpw"
    image_tag: "1.4.4"

  # Only use this field when you have a docker repository.
  repo:
    # the url defines docker hub project access point
    # official hub - url: "hyperledger/",
    # fabric build hub - url: "nexus3.hyperledger.org:10001/hyperledger/",
    url: "hyperledger/"
    username: ""
    password: ""

    # locations to download fabric binaries. This url should point to a
    # compressed such as tar or zip file which contains necessary binaries
    # such as configtxgen, configtxlator, cryptogen etc.
    bin: "https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric/linux-amd64-1.4.4/hyperledger-fabric-linux-amd64-1.4.4.tar.gz"