---
# This variable defines fabric network attributes
fabric:
  peer_db: "goleveldb"
  tls: true
  consensus_type: "kafka"
  logging_level: "ERROR"
  k8s:
    exposeserviceport: True
    storageclass: "ibmc-file-gold"
    storagecapacity: "20Gi"
    shared_storage: false
    mem_req: "512Mi"
    mem_limit: "1024Mi"
    cpu_req: "0.1"
    cpu_limit: "0.2"
    # only used when exposeserviceport set to be true
    # the value could be NodePort or LoadBalancer
    servicetype: NodePort

  network:
    fabric001:
      cas: ["ca1st.orgc"]
      peers: []
      orderers: ["orderer1st.orgc","orderer2nd.orgc","orderer3rd.orgc"]
      zookeepers: ["zookeeper1st","zookeeper2nd","zookeeper3rd"]
      kafkas: ["kafka1st","kafka2nd","kafka3rd"]

  baseimage_tag: "1.4.4"
  helper_tag: "0.4.18"
  ca:
    admin: "admin"
    adminpw: "adminpw"
    image_tag: "1.4.4"

  repo:
    url: "hyperledger/"
    username: ""
    password: ""
    bin: "https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric/linux-amd64-1.4.4/hyperledger-fabric-linux-amd64-1.4.4.tar.gz"