---
# This variable defines fabric network attributes
fabric:

  # options are "goleveldb", "CouchDB", default is goleveldb
  peer_db: "goleveldb"
  tls: true
  logging_level: "ERROR"
  k8s:
    exposeserviceport: True
    storageclass: "default"
    storagecapacity: "20Gi"
    shared_storage: false
    mem_req: "512Mi"
    mem_limit: "1024Mi"
    cpu_req: "0.1"
    cpu_limit: "0.2"
    # only used when exposeserviceport set to be true
    # the value could be NodePort or LoadBalancer
    servicetype: LoadBalancer

  orderersettings:
    config:
      BatchTimeout: 10s
    ordererenv:
      ORDERER_GENERAL_PROFILE_ENABLED: false

  network:
    fabric001:
      cas: []
      peers: ["worker@peer1st.orgt","worker@peer2nd.orgt","worker@peer3rd.orgt"]
      orderers: []
      zookeepers: []
      kafkas: []

  baseimage_tag: "1.4.4"
  helper_tag: "1.4.4"
  ca:
    admin: "admin"
    adminpw: "adminpw"
    image_tag: "1.4.4"

  repo:
    url: "hyperledger/"
    username: ""
    password: ""
    bin: "https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric/linux-amd64-1.4.4/hyperledger-fabric-linux-amd64-1.4.4.tar.gz"
